### ISSUE TITLE
No task information in money game [1 class difficulty]

### ISSUE THREAD

**Issue by michal1000w** [Madoxen/EducationalAdventure#87]

**Comment by michal1000w** [comment]
![61462607_329526937721778_1089222801690198016_n](https://user-images.githubusercontent.com/19635319/58506031-a7ad4380-818e-11e9-9929-02d3486922d7.png)

**Comment by zwalone** [comment]
it's work for 20 PLN

**Comment by michal1000w** [comment]
I know and I've finished it all but there should be text saying how much or otherwise noone will know
